stylesheets:
  - href: "/rss.xsl"
    media: "all"
    type: "text/xsl"

headers:
  "User-Agent": "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"

feeds:
  example:
    channel:
      url: https://github.com/html2rss/html2rss-web/commits/master
      title: Latest commits on html2rss-web's master branch.
      ttl: 120
    selectors:
      items:
        selector: "li > div"
      title:
        selector: "h4"
      url:
        selector: "a"
        extractor: "href"

  hn_front:
    channel:
      url: https://news.ycombinator.com/
      title: "Hacker News (home)"
      ttl: 120
    selectors:
      items:
        selector: "tr.athing"
      title:
        selector: "span.titleline a"
      url:
        selector: "span.titleline a"
        extractor: "href"
feeds:
  spicy4tuna_newsletter:
    channel:
      url: https://newsletter.spicy4tuna.com/
      title: SPICY4TUNA Newsletter
      description: "Resumen de los últimos episodios y contenido extra"
      ttl: 120
    selectors:
      items:
        selector: "#### Publicaciones ~ ul > li" # Lista de entradas
      title:
        selector: "a" # El texto del enlace
      url:
        selector: "a"
        extractor: "href"
      # Opcional: fecha si estuviera visible
